<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="5" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-20T13:54:39 GMT" name="Surefire suite" finished-at="2025-06-20T13:54:40 GMT" duration-ms="1041">
    <groups>
    </groups>
    <test started-at="2025-06-20T13:54:39 GMT" name="Surefire test" finished-at="2025-06-20T13:54:40 GMT" duration-ms="1041">
      <class name="com.elitekaycy.testlabs.labs.QuickSortTest">
        <test-method signature="test_quicksort_with_data_providers([I)[pri:0, instance:com.elitekaycy.testlabs.labs.QuickSortTest@6b4a4e18]" started-at="2025-06-20T13:54:40 GMT" name="test_quicksort_with_data_providers" data-provider="sortData" finished-at="2025-06-20T13:54:40 GMT" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[I@1ad777f]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_quicksort_with_data_providers -->
        <test-method signature="unit_test_quicksort()[pri:0, instance:com.elitekaycy.testlabs.labs.QuickSortTest@6b4a4e18]" started-at="2025-06-20T13:54:40 GMT" name="unit_test_quicksort" finished-at="2025-06-20T13:54:40 GMT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unit_test_quicksort -->
        <test-method signature="test_quicksort_with_data_providers([I)[pri:0, instance:com.elitekaycy.testlabs.labs.QuickSortTest@6b4a4e18]" started-at="2025-06-20T13:54:40 GMT" name="test_quicksort_with_data_providers" data-provider="sortData" finished-at="2025-06-20T13:54:40 GMT" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[I@25230246]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_quicksort_with_data_providers -->
      </class> <!-- com.elitekaycy.testlabs.labs.QuickSortTest -->
      <class name="com.elitekaycy.testlabs.labs.MockTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003]" started-at="2025-06-20T13:54:39 GMT" name="setUp" finished-at="2025-06-20T13:54:40 GMT" duration-ms="916" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testGetUserSuccess()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003]" started-at="2025-06-20T13:54:40 GMT" name="testGetUserSuccess" finished-at="2025-06-20T13:54:40 GMT" duration-ms="48" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUserSuccess -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003]" started-at="2025-06-20T13:54:40 GMT" name="tearDown" finished-at="2025-06-20T13:54:40 GMT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003]" started-at="2025-06-20T13:54:40 GMT" name="setUp" finished-at="2025-06-20T13:54:40 GMT" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testGetUserWithWrongEmailThrowsException()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003]" started-at="2025-06-20T13:54:40 GMT" name="testGetUserWithWrongEmailThrowsException" finished-at="2025-06-20T13:54:40 GMT" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method MockTest.testGetUserWithWrongEmailThrowsException()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003] should have thrown an exception of type class java.lang.IllegalArgumentException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method MockTest.testGetUserWithWrongEmailThrowsException()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003] should have thrown an exception of type class java.lang.IllegalArgumentException
at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
at org.testng.internal.invokers.TestInvoker.considerExceptionsInternal(TestInvoker.java:895)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:860)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:741)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUserWithWrongEmailThrowsException -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003]" started-at="2025-06-20T13:54:40 GMT" name="tearDown" finished-at="2025-06-20T13:54:40 GMT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003]" started-at="2025-06-20T13:54:40 GMT" name="setUp" finished-at="2025-06-20T13:54:40 GMT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testGetUserWithWrongNameThrowsException()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003]" started-at="2025-06-20T13:54:40 GMT" name="testGetUserWithWrongNameThrowsException" finished-at="2025-06-20T13:54:40 GMT" duration-ms="2" status="FAIL">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method MockTest.testGetUserWithWrongNameThrowsException()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003] should have thrown an exception of type class java.lang.IllegalArgumentException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method MockTest.testGetUserWithWrongNameThrowsException()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003] should have thrown an exception of type class java.lang.IllegalArgumentException
at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
at org.testng.internal.invokers.TestInvoker.considerExceptionsInternal(TestInvoker.java:895)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:860)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:741)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUserWithWrongNameThrowsException -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.elitekaycy.testlabs.labs.MockTest@3b938003]" started-at="2025-06-20T13:54:40 GMT" name="tearDown" finished-at="2025-06-20T13:54:40 GMT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.elitekaycy.testlabs.labs.MockTest -->
      <class name="com.elitekaycy.testlabs.DemoTest">
        <test-method signature="sample()[pri:0, instance:com.elitekaycy.testlabs.DemoTest@4b168fa9]" started-at="2025-06-20T13:54:39 GMT" name="sample" finished-at="2025-06-20T13:54:39 GMT" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sample -->
      </class> <!-- com.elitekaycy.testlabs.DemoTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
